filebeat.inputs:
- type: docker
  enabled: true
  containers.ids:
    - "*"

output.logstash:
  hosts: ["elasticsearch:9200"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

logging.json: true
logging.metrics.enabled: false%